### ISSUE TITLE
Assert::that()->numeric() being marked as "always evaluate to true"

### ISSUE THREAD

**Issue by lcobucci** [phpstan/phpstan-beberlei-assert#11]
For the following code:

```php
class Bar
{
    public function doBar(string $s)
    {
        Assert::that($s)->numeric();
    }
}
```

We're always getting the error:

```sh
# Call to method Assert\AssertionChain::numeric() will always evaluate to true.
```

I don't believe this is quite right, since we might have non-numeric strings, correct? Or are we doing something wrong?

**Comment by ondrejmirtes** [comment]
Should be solved on dev-master of PHPStan (https://github.com/phpstan/phpstan-src/commit/53a5171d6de3313c5736de49f751b659ab9b07d8) :) I'll release it as 0.12.15 later today so please test it :) Thank you!
