### ISSUE TITLE
Invalid Assertion::eq evaluation

### ISSUE THREAD

**Issue by simPod** [phpstan/phpstan-beberlei-assert#5]
```php
    private function first()
    {
        $var = getenv('env');
        Assertion::eq($var, 'value');
        $this->second($var);
    }

    private function second(string $needsString)
    {

    }
```

Returns
> Parameter #1 $needsString of method ::second() expects string, string|false given.

Even though we know the possible set of types for `$var` is `string` when passed into `second()`. Or am I wrong?

**Comment by ondrejmirtes** [comment]
Is `eq` the equivalent to `==` or `===`? Anyway, adding another assertion to `string()` will not kill you ;)

**Comment by simPod** [comment]
I see, there's `::same` method ;) thanks
